; app.inc - アプリケーション
; 


; ゼロページ
;
APP_0                               :=  $e0
APP_0_PROC                          :=  $e0
APP_0_PROC_L                        :=  $e0
APP_0_PROC_H                        :=  $e1
APP_0_STATE                         :=  $e2
APP_0_COUNT                         :=  $e3
APP_0_USER                          :=  $e4
APP_0_USER_END                      :=  $fb
APP_0_WORK_0                        :=  $fc
APP_0_WORK_1                        :=  $fd
APP_0_WORK_2                        :=  $fe
APP_0_WORK_3                        :=  $ff

